package Demo2.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Demo2_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("0d40d465-dded-40d0-8d4c-2c6d177f60d7(Demo2)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
