package Demo2.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class Constant_Constraints extends BaseConstraintsDescriptor {
  public Constant_Constraints() {
    super("Demo2.structure.Constant");
  }
}
