package Demo2.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class IntroduceConstant_Intention extends BaseIntention implements Intention {
  public IntroduceConstant_Intention() {
  }

  public String getConcept() {
    return "jetbrains.mps.baseLanguage.structure.Expression";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "Introduce Constant";
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(this.isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  public boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return SNodeOperations.getAncestor(node, "Demo2.structure.Constant", false, false) != null;
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SNode constant = SConceptOperations.createNewNode("Demo2.structure.Constant", null);
    SNodeOperations.insertPrevSiblingChild(SNodeOperations.getAncestor(node, "Demo2.structure.Constant", false, false), constant);
    SNode constantReference = SConceptOperations.createNewNode("Demo2.structure.ConstantReference", null);
    SLinkOperations.setTarget(constantReference, "original", constant, false);
    SNodeOperations.replaceWithAnother(node, constantReference);
    SLinkOperations.setTarget(constant, "initializer", node, true);
    editorContext.selectWRTFocusPolicy(constant);
  }

  public String getLocationString() {
    return "Demo2.intentions";
  }
}
